// <auto-generated />
using AssistClickY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssistClickY.Migrations
{
    [DbContext(typeof(AssistClickYContext))]
    partial class AssistClickYContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("AssistClickY.Models.Hotkey", b =>
                {
                    b.Property<int>("HotkeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HotkeyCombination")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotkeyJob")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierKeys")
                        .HasColumnType("INTEGER");

                    b.HasKey("HotkeyId");

                    b.ToTable("Hotkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
